server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Joowon-Seo/Spring-Cloud-Config-Of-MSA_Ecommerce
#          uri: file://C:\Portfolio\git-rocal-repo
